--drop table if exists user CASCADE;
create table user (
user_id bigint(20) generated by default as identity,
username varchar(50),
password varchar(100),
nickname varchar(50),
activated tinyint,
primary key (user_id)
);

--drop table if exists USER_AUTHORITY CASCADE;
create table USER_AUTHORITY (user_id bigint(20),authority_name varchar(50));

--drop table if exists AUTHORITY CASCADE;
create table AUTHORITY (authority_name varchar(50));